import type { NextPage } from "next";
import Head from "next/head";

import { ArticleList } from "../Components/Home/ArticleList";
import { FixedHomeTabOutlet } from "../Components/Home/FixedHomeTabOutlet";
import { FixedHeaderHome } from "../Components/Home/FixedHeaderHome";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FixedHeaderHome />
      <ArticleList />
      <FixedHomeTabOutlet />
    </>
  );
};

export default Home;
