import type { NextPage } from "next";
import Head from "next/head";
import {
  FixedHeaderHome,
  FixedTabOutlet,
} from "../Components/Home/FixedHeaderHome";
import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen  bg-slate-900 dark">
        <FixedHeaderHome />
        <div>
          <span className="text-4xl text-white">OI</span>
        </div>
        <FixedTabOutlet />
      </main>
    </>
  );
};

export default Home;
