import type { NextPage } from "next";
import Head from "next/head";

import { ArticleList } from "../Components/Home/ArticleList";
import { FixedTabOutlet } from "../Components/Home/FixedHomeTabOutlet";
import { FixedHeaderHome } from "../Components/Home/FixedHeaderHome";

import { trpc } from "../utils/trpc";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FixedHeaderHome />
      <ArticleList />
      <FixedTabOutlet />
    </>
  );
};

export default Home;
